### ISSUE TITLE
UML Diagram | Use Case Diagram

### ISSUE THREAD

**Issue by Zasaimster** [Zasaimster/ByteSize-Insights#26]
## User Story
Describe the use cases of your application and the actors and external systems involved in them with a Use Case Diagram. Please include one use case diagram for the entire application.

## Acceptance Criteria
- [x] Completed use case diagram.

**Comment by aidenszeto** [comment]
![Image](https://github.com/Zasaimster/ByteSize-Insights/assets/66970460/e7f3a2bd-761d-4bb8-b93c-31b6ce3cf4bd)
