### ISSUE TITLE
UML Diagram | Activity Diagrams

### ISSUE THREAD

**Issue by Zasaimster** [Zasaimster/ByteSize-Insights#27]
## User Story
Describe the actions of each actor and system and the control flow between them for your most important use cases with Activity Diagrams. Please include one or two activity diagrams showing your most important components in your application.

We want to create one activity diagram to indicate the user flow and another activity diagram for the chron job flow which is in charge of periodically scraping the Github PRs.

## Acceptance Criteria
- [x] User activity diagram
- [x] Chron job activity diagram

**Comment by NFJ1618** [comment]
![Activity UML User](https://github.com/Zasaimster/ByteSize-Insights/assets/67336232/66f031bc-1851-406b-a7af-0e9a6d60e002)

**Comment by NFJ1618** [comment]
![UML Activity Diagram Cron](https://github.com/Zasaimster/ByteSize-Insights/assets/67336232/1f8eaaac-171e-446e-947b-f41ef32884f5)
