### ISSUE TITLE
UML Diagram | State Machine Diagrams

### ISSUE THREAD

**Issue by Zasaimster** [Zasaimster/ByteSize-Insights#30]
## User Story
Describe the behavior of your most complex classes (of the system as a whole) and how it responds to events with State Machine Diagrams. We want one a state machine diagram to describe a user's flow between pages and one to describe the state of the pull request information as it gets pulled from the Github API to eventually transforming into a summary provided by ChatGPT.

## Acceptance Criteria
- [x] Completed user flow state machine diagram
- [x] Completed pull request state machine diagram

**Comment by aidenszeto** [comment]
![Image](https://github.com/Zasaimster/ByteSize-Insights/assets/66970460/dd8fcb17-e50a-4f5e-9dfe-ac8b9b0047e9)
![Image](https://github.com/Zasaimster/ByteSize-Insights/assets/66970460/736e0975-2b34-4bfb-9079-fc270d872644)
